### ISSUE TITLE
反射获取ViewBinding的时候进行强转 报错了

### ISSUE THREAD

**Issue by gentlemanxzh** [DylanCaiCoding/ViewBindingKtx#8]
主要是因为ViewBinding.java
` protected static <T extends ViewDataBinding> T inflateInternal(
            @NonNull LayoutInflater inflater, int layoutId, @Nullable ViewGroup parent,
            boolean attachToParent, @Nullable Object bindingComponent) {
        return DataBindingUtil.inflate(
                inflater,
                layoutId,
                parent,
                attachToParent,
                checkAndCastToBindingComponent(bindingComponent)
        );
    }`
这个方法返回的不是FragmentLoginAccountBinding而是FragmentLoginAccountBindingImpl

Caused by: java.lang.ClassCastException: com.quicktalk.im.databinding.FragmentLoginAccountBindingImpl cannot be cast to com.quicktalk.login.databinding.FragmentLoginAccountBinding
        at com.quicktalk.login.databinding.FragmentLoginAccountBinding.inflate(FragmentLoginAccountBinding.java:96)
2021-01-30 14:25:27.618 23722-23722/com.quicktalk.im E/AndroidRuntime:     at com.quicktalk.login.databinding.FragmentLoginAccountBinding.inflate(FragmentLoginAccountBinding.java:82)
        	... 41 more

**Comment by DylanCaiCoding** [comment]
请问下你是怎么使用的？

**Comment by gentlemanxzh** [comment]
> 请问下你是怎么使用的？

是我的问题，主module和子module有同名的layout布局
